// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pdsl.Api.Data;

#nullable disable

namespace Pdsl.Api.Migrations
{
    [DbContext(typeof(PdslDbContext))]
    [Migration("20220403114235_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Pdsl.Api.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LocatorId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Suffix")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("LocatorId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = -111,
                            FirstName = "Hafiz",
                            LastName = "Pussah",
                            LocatorId = "bb9f3ef8-b64e-4d37-ba48-6a7bac99a9a3",
                            MiddleName = "Mohamed",
                            Title = "Admin"
                        });
                });

            modelBuilder.Entity("Pdsl.Api.Data.PressRelease", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DataFilePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HeroImageFilePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LocatorId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("ReleaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("UploaderId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocatorId")
                        .IsUnique();

                    b.HasIndex("UploaderId");

                    b.ToTable("PressReleases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "beb6fc9d-4b8c-4738-8f1c-038bcec82e0c",
                            ReleaseDate = new DateTime(2020, 4, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1483),
                            Title = "2 Years Ago",
                            UploadDate = new DateTime(2020, 4, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1490),
                            UploaderId = -111
                        },
                        new
                        {
                            Id = 2,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "beb6fc9d-4b8c-4738-8f1c-038bcec82e0b",
                            ReleaseDate = new DateTime(2019, 4, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1492),
                            Title = "3 Years Ago",
                            UploadDate = new DateTime(2019, 4, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1493),
                            UploaderId = -111
                        },
                        new
                        {
                            Id = 3,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "deb6fc9d-4b8c-4738-8f1c-038bcec82e09",
                            ReleaseDate = new DateTime(2021, 7, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1494),
                            Title = "9 Months Ago",
                            UploadDate = new DateTime(2021, 7, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1496),
                            UploaderId = -111
                        },
                        new
                        {
                            Id = 4,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "ceb6fc9d-4b8c-4738-8f1c-038bcec82e09",
                            ReleaseDate = new DateTime(2021, 8, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1497),
                            Title = "8 Months Ago",
                            UploadDate = new DateTime(2021, 8, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1498),
                            UploaderId = -111
                        },
                        new
                        {
                            Id = 5,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "bec6fc9d-4b8c-4728-8f1c-038bcec82e09",
                            ReleaseDate = new DateTime(2021, 7, 24, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1499),
                            Title = "8 Months Ago",
                            UploadDate = new DateTime(2021, 8, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1503),
                            UploaderId = -111
                        },
                        new
                        {
                            Id = 6,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "beb6fc9d-4b8c-4738-8f1c-038b3ec82e09",
                            ReleaseDate = new DateTime(2021, 7, 29, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1504),
                            Title = "8 Months",
                            UploadDate = new DateTime(2021, 8, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1505),
                            UploaderId = -111
                        },
                        new
                        {
                            Id = 7,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "beb6fc9d-4b8c-4738-8f1c-038bcec82e19",
                            ReleaseDate = new DateTime(2022, 2, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1506),
                            Title = "2 Months Ago",
                            UploadDate = new DateTime(2022, 2, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1507),
                            UploaderId = -111
                        },
                        new
                        {
                            Id = 8,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "beb6fc9d-3b8c-4738-8f1c-038bcec82e09",
                            ReleaseDate = new DateTime(2022, 3, 4, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1508),
                            Title = "1 Month Ago",
                            UploadDate = new DateTime(2022, 3, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1509),
                            UploaderId = -111
                        },
                        new
                        {
                            Id = 9,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "beb6f99d-4b8c-4738-8f1c-038bcec82e09",
                            ReleaseDate = new DateTime(2022, 3, 24, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1511),
                            Title = "10 Days Ago",
                            UploadDate = new DateTime(2022, 3, 24, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1511),
                            UploaderId = -111
                        },
                        new
                        {
                            Id = 10,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "bee6fc9d-4b8c-4738-8f1c-038bcec82e09",
                            ReleaseDate = new DateTime(2022, 3, 24, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1512),
                            Title = "10 Days Ago Another",
                            UploadDate = new DateTime(2022, 3, 24, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1512),
                            UploaderId = -111
                        },
                        new
                        {
                            Id = 11,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "beb6fc9d-4b8c-4738-8f1c-038bcec82e09",
                            ReleaseDate = new DateTime(2022, 3, 26, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1543),
                            Title = "8 Days Ago",
                            UploadDate = new DateTime(2022, 3, 26, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1544),
                            UploaderId = -111
                        },
                        new
                        {
                            Id = 12,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "beb6fc9d-4b8c-4728-8f1c-038bcec82e09",
                            ReleaseDate = new DateTime(2022, 3, 28, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1545),
                            Title = "6 Days Ago",
                            UploadDate = new DateTime(2022, 3, 28, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1546),
                            UploaderId = -111
                        },
                        new
                        {
                            Id = 13,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "beb6fc9d-4b8c-4738-811c-038bcec82e09",
                            ReleaseDate = new DateTime(2022, 3, 20, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1547),
                            Title = "14 Days Ago",
                            UploadDate = new DateTime(2022, 3, 20, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1547),
                            UploaderId = -111
                        },
                        new
                        {
                            Id = 14,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "beb6fc9d-4b8c-4738-8f1c-038b2ec82e09",
                            ReleaseDate = new DateTime(2022, 4, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1548),
                            Title = "Today",
                            UploadDate = new DateTime(2022, 4, 3, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1549),
                            UploaderId = -111
                        },
                        new
                        {
                            Id = 15,
                            Abstract = "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                            DataFilePath = "a393cfbf-97af-4ccf-95b6-e19c9ffcf519.pdf",
                            HeroImageFilePath = "a047e9fe-581d-481a-9adc-bc5510fbc93e.jpg",
                            LocatorId = "beb6fc9d-4b5c-4738-8f1c-038bcec82e09",
                            ReleaseDate = new DateTime(2022, 4, 1, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1550),
                            Title = "2 Days Ago",
                            UploadDate = new DateTime(2022, 4, 1, 11, 42, 34, 796, DateTimeKind.Utc).AddTicks(1550),
                            UploaderId = -111
                        });
                });

            modelBuilder.Entity("Pdsl.Api.Data.PressRelease", b =>
                {
                    b.HasOne("Pdsl.Api.Data.Employee", "Uploader")
                        .WithMany("PressReleases")
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Pdsl.Api.Data.Employee", b =>
                {
                    b.Navigation("PressReleases");
                });
#pragma warning restore 612, 618
        }
    }
}
